Exercise 1

In [2]:
%%timeit
L = [i ** 2 for i in range(1000000)]

109 ms ± 7.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
import numpy

In [4]:
%%timeit
L2 = numpy.arange(1000000) ** 2

3.02 ms ± 260 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


NumPy arrays are faster than Python lists because they hold their data at one continuous block of memory, which allows for efficient access.
In contrast, Python lists may not hold their data continuously, instead storing it across multiple locations. This can lead to fragmented memory, which decreases the efficiency of memory access.

Exercise 2

In [5]:
rng = numpy.random.default_rng(1234)

M = rng.integers(10, size=(4, 4))
print("Shape:", M.shape)
print("Size:", M.size)
print("Number of Dimensions:", M.ndim)
print(M)

Shape: (4, 4)
Size: 16
Number of Dimensions: 2
[[9 9 9 3]
 [1 9 1 2]
 [1 3 5 1]
 [7 2 7 3]]


Exercise 3

In [6]:
im = numpy.identity(3)
print(im)

rng = numpy.random.default_rng(5678)
arr = rng.integers(low=1, high=100, size=20)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 5 92 43 67 18 67 30 53 19 80 65 78 56 19 91 51 88 72 28 57]


Exercise 4

In [7]:
M = numpy.array([[ 1,  2,  3,  4,  5],
                 [ 6,  7,  8,  9, 10],
                 [11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20],
                 [21, 22, 23, 24, 25]])

print("Third row:", M[2])
print("Last two columns:\n", M[:, 3:5])
print("3x3 submatrix from the center:\n", M[1:4, 1:4])

Third row: [11 12 13 14 15]
Last two columns:
 [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]
3x3 submatrix from the center:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Exercise 5

In [8]:
arr2 = numpy.arange(1, 21)
print("Before reshaping:", arr2)

arr2 = arr2.reshape(4, 5)
print("After reshaping:\n", arr2)

Before reshaping: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After reshaping:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
